<script setup lang="ts">
import { computed, ref } from 'vue'
import type { Game } from '../types'
const props=defineProps<{game:Game;loading:boolean;streamed:string}>()
const emit=defineEmits<{act:[text:string];accuse:[suspect:string,reasoning:string];newCase:[]}>()
const input=ref(''); const tab=ref<'evidence'|'suspects'>('evidence'); const showAccuse=ref(false); const selected=ref(''); const reasoning=ref('')
const location=computed(()=>props.game.locations.find(x=>x.id===props.game.current_location_id)!)
function send(text=input.value){ if(!text.trim())return; emit('act',text); input.value='' }
function confirm(){if(selected.value&&reasoning.value.trim()){emit('accuse',selected.value,reasoning.value);showAccuse.value=false}}
</script>
<template><div class="game-shell">
  <header><b>CASE: <i>UNKNOWN</i></b><span class="file-no">{{game.id.slice(0,8)}} · ACTIVE FILE</span><button class="ghost" @click="emit('newCase')">새 사건</button></header>
  <aside class="case-file"><small>CASE FILE / {{game.genre}}</small><h2>{{game.title}}</h2><p>{{game.incident_summary}}</p><div class="progress"><span :style="{width:`${Math.min(100,game.evidence.length/7*100)}%`}"></span></div><small>{{game.evidence.length}} EVIDENCE RECOVERED</small><h3>LOCATIONS</h3><button v-for="loc in game.locations" :key="loc.id" class="nav-item" :class="{active:loc.id===game.current_location_id}" :disabled="loc.locked" @click="send(`${loc.name}로 이동`)" :aria-label="loc.name"><span>{{loc.locked?'▣':'◇'}}</span>{{loc.name}}</button>
  <h3>QUICK ACTIONS</h3><button class="quick" @click="send('주변을 자세히 조사해')">⌕ 주변 조사</button><button class="quick" @click="send('현재 증거 정리해줘')">≡ 증거 정리</button></aside>
  <main class="investigation"><div class="scene"><img :src="location.image_url" :alt="location.name"><div><small>CURRENT LOCATION</small><h2>{{location.name}}</h2><p>{{location.description}}</p></div></div><section class="log" aria-live="polite"><article v-for="(line,i) in game.narratives" :key="i" :class="i===game.narratives.length-1?'latest':''"><small>{{i===0?'CASE BRIEF':'FIELD NOTE'}}</small><p>{{i===game.narratives.length-1&&streamed?streamed:line}}</p></article></section><form @submit.prevent="send()"><label for="action">무엇을 조사하시겠습니까?</label><div class="input-row"><input id="action" v-model="input" :disabled="loading||game.completed" placeholder="예: CCTV와 출입 기록을 확인해"><button :disabled="loading||!input.trim()">전송</button></div></form></main>
  <aside class="board"><nav><button :class="{active:tab==='evidence'}" @click="tab='evidence'">EVIDENCE {{game.evidence.length}}</button><button :class="{active:tab==='suspects'}" @click="tab='suspects'">SUSPECTS</button></nav><div v-if="tab==='evidence'" class="card-grid"><article v-for="item in game.evidence" :key="item.id" class="evidence-card"><img v-if="item.image_url" :src="item.image_url" :alt="item.title"><small>{{item.category}}</small><h4>{{item.title}}</h4><p>{{item.description}}</p></article><div v-if="!game.evidence.length" class="empty">아직 확보한 증거가 없습니다.<br>현장을 조사하세요.</div></div><div v-else class="suspects"><article v-for="s in game.suspects" :key="s.id"><img :src="s.portrait_url" :alt="s.name"><div><h4>{{s.name}}</h4><small>{{s.role}}</small><p>{{s.public_profile}}</p><button class="quick" @click="send(`${s.name}에게 알리바이를 물어봐`)">심문</button></div></article></div><button class="accuse" :disabled="game.completed" @click="showAccuse=true">용의자 고발</button></aside>
  <nav class="mobile-nav"><button>수사</button><button @click="tab='evidence'">증거</button><button @click="tab='suspects'">용의자</button></nav>
  <div v-if="showAccuse" class="modal" @click.self="showAccuse=false"><section><small>FINAL ACCUSATION</small><h2>한 번의 고발로 사건이 끝납니다.</h2><label>용의자<select v-model="selected"><option value="" disabled>선택</option><option v-for="s in game.suspects" :value="s.id" :key="s.id">{{s.name}}</option></select></label><label>추론<textarea v-model="reasoning" placeholder="증거를 연결해 설명하세요"></textarea></label><div><button class="ghost" @click="showAccuse=false">취소</button><button class="accuse" :disabled="!selected||reasoning.length<3" @click="confirm">고발 확정</button></div></section></div>
  <div v-if="game.completed" class="modal resolution"><section><small>{{game.won?'CASE SOLVED':'CASE FAILED'}}</small><h2>{{game.won?'진실을 밝혀냈습니다.':'진실은 다른 곳에 있었습니다.'}}</h2><p>{{game.solution?.summary}}</p><dl><dt>범행 시각</dt><dd>{{game.solution?.crime_time}}</dd><dt>동기</dt><dd>{{game.solution?.motive}}</dd><dt>수법</dt><dd>{{game.solution?.crime_method}}</dd></dl><ol><li v-for="step in game.solution?.timeline" :key="step">{{step}}</li></ol><button @click="emit('newCase')">NEW CASE</button></section></div>
</div></template>
